name: windows

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        ocaml-compiler:
          - "ocaml.5.0.0,ocaml-option-mingw"
          - "ocaml.5.1.1,ocaml-option-mingw"
          - "ocaml.5.2.0,ocaml-option-mingw"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: |
            dra27: https://github.com/dra27/opam-repository.git#windows-5.0
            default: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
            standard: https://github.com/ocaml/opam-repository.git
          opam-local-packages: |
            grpc.opam
            grpc-lwt.opam
            grpc-eio.opam

      - name: Install dependencies
        run: opam install ./grpc.opam ./grpc-lwt.opam ./grpc-eio.opam --deps-only --with-test

      - name: Build
        run: opam exec -- dune build lib/grpc lib/grpc-lwt lib/grpc-eio
